framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'antonelamaciel2024@gmail.com'
        headers:
            from: 'Tu Tienda <antonelamaciel2024@gmail.com>'